# Generated by Django 2.2.9 on 2019-12-28 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('background', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.TextField()),
                ('date', models.DateTimeField()),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('artsy', 'Artsy'), ('boozey', 'Boozey'), ('charity', 'Charity'), ('craftsy', 'Craftsy'), ('foody', 'Foody'), ('musicy', 'Musicy'), ('petsy', 'Petsy')], max_length=100)),
                ('reach', models.CharField(choices=[('local', 'Local'), ('regional', 'Regional'), ('national', 'National')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('background', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=250)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('country', models.CharField(default='US', max_length=250)),
                ('zipcode', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='')),
                ('background', models.ImageField(blank=True, null=True, upload_to='')),
                ('short_description', models.TextField(blank=True, null=True)),
                ('business_url', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('organizer', 'Organizer')], max_length=20)),
                ('attends', models.ManyToManyField(related_name='attendees', to='general.Event')),
                ('follows', models.ManyToManyField(related_name='followers', to='general.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Venue'),
        ),
    ]
